"""delete used_by

Revision ID: 101be3fffe06
Revises: 890508c24564
Create Date: 2019-01-11 23:03:33.053472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101be3fffe06'
down_revision = '890508c24564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.alter_column('last_used_by', new_column_name='holder')
        # 'fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s'
        # batch_op.drop_constraint(op.f('drop last_used_by'), type_='foreignkey')
        # batch_op.drop_column('last_used_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_used_by', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['last_used_by'], ['id'])

    # ### end Alembic commands ###
