"""add location columns

Revision ID: 3eac492c23d5
Revises: 4727f2176ebd
Create Date: 2019-01-12 23:46:20.202920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eac492c23d5'
down_revision = '4727f2176ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=64), nullable=True))

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_in', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('location_out', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('location_out')
        batch_op.drop_column('location_in')

    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
