"""log table

Revision ID: 4727f2176ebd
Revises: 101be3fffe06
Create Date: 2019-01-12 12:41:00.417848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4727f2176ebd'
down_revision = '101be3fffe06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('bike', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
