"""delete last_used column

Revision ID: 890508c24564
Revises: f473bc065eea
Create Date: 2019-01-10 09:58:55.377055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890508c24564'
down_revision = 'f473bc065eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike') as batch_op:
        batch_op.drop_column('last_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('last_used', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
