"""delete bike location column

Revision ID: b0d5babecb38
Revises: 3eac492c23d5
Create Date: 2019-01-13 14:00:51.256493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d5babecb38'
down_revision = '3eac492c23d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
