"""delete post and add bike

Revision ID: f473bc065eea
Revises: 3b04e358d717
Create Date: 2018-12-26 19:23:14.246631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f473bc065eea'
down_revision = '3b04e358d717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('out of service', 'available', 'in use', name='status'), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('last_used_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_used_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bike_number'), 'bike', ['number'], unique=True)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_bike_number'), table_name='bike')
    op.drop_table('bike')
    # ### end Alembic commands ###
